//! Full-length production contribution generation for the Dory V3 model ceremony.
//!
//! The public entry point has no seed or geometry inputs. It rejection-samples
//! directly from the operating-system CSPRNG into the one frozen production
//! length, then reopens and authenticates the retained output before success.
//! Its JSON report is operational output, not ceremony transcript evidence.
//!
//! Publication assumes the operator-owned local-directory boundary required by
//! the ceremony protocol. A crash can leave a partial file that must be
//! quarantined; this module does not claim safety in a hostile shared directory.
//! On Windows, an operator-only parent-directory DACL is a prerequisite that
//! this portable implementation does not attempt to infer.

use std::{
    fs::{self, File, OpenOptions},
    io::{Read, Write},
    path::{Path, PathBuf},
    time::{Duration, Instant},
};

use rand_core::{OsRng, RngCore};
use same_file::Handle as SameFileHandle;
use serde::Serialize;
use sha2::{Digest as _, Sha256};
use thiserror::Error;

use crate::{
    MAX_MODEL_BYTE,
    dory_v3_suite::{DORY_V3_BATCH, DORY_V3_DIMENSION, DORY_V3_LAYERS, Digest32},
};

const FROZEN_PRODUCTION_CONTRIBUTION_BYTES: u64 = 6_442_975_232;
const PRODUCTION_BUFFER_BYTES: usize = 1_048_576;

/// Audit-only result emitted after the generated contribution has been
/// reopened, range-checked, dual-hashed, and identity-checked.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct ProductionDoryV3ModelContributionReport {
    pub output: PathBuf,
    pub contribution_bytes: u64,
    pub source_bytes_consumed: u64,
    pub rejected_source_bytes: u64,
    pub contribution_blake3: Digest32,
    pub contribution_sha256: Digest32,
    pub generation_elapsed_micros: u64,
    pub verification_elapsed_micros: u64,
}

/// Fail-closed errors from full-length production contribution generation.
#[derive(Debug, Error)]
pub enum ProductionDoryV3ModelContributionError {
    #[error("the compiled production contribution geometry overflowed")]
    GeometryOverflow,
    #[error("the compiled production contribution geometry is not the frozen ceremony geometry")]
    ProductionGeometryMismatch,
    #[error("refusing to run because the output path already exists: {0}")]
    OutputExists(PathBuf),
    #[error("output path is not an ordinary local file path: {0}")]
    InvalidOutputPath(PathBuf),
    #[error("output parent is not a real non-reparse directory: {0}")]
    UnsafeOutputParent(PathBuf),
    #[error("failed to inspect output path {path}: {source}")]
    InspectOutput {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to create new output file {path}: {source}")]
    CreateOutput {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("the operating-system CSPRNG failed: {0}")]
    Entropy(#[source] rand_core::Error),
    #[error("generation byte accounting overflowed")]
    CountOverflow,
    #[error("failed to allocate the bounded generation buffer")]
    BufferAllocation,
    #[error("failed to write new output file {path}: {source}")]
    WriteOutput {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to flush new output file {path}: {source}")]
    FlushOutput {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to sync new output file {path}: {source}")]
    SyncOutput {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to reopen or read output file {path}: {source}")]
    ReadOutput {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("output path is not a regular file: {0}")]
    OutputNotRegular(PathBuf),
    #[error("output file has {links} hard links instead of exactly one: {path}")]
    UnexpectedHardLinks { path: PathBuf, links: u64 },
    #[error("this target cannot verify that the output has exactly one hard link: {0}")]
    HardLinkCountUnsupported(PathBuf),
    #[error("output path was replaced or no longer names the retained file: {0}")]
    OutputIdentityMismatch(PathBuf),
    #[error("output length mismatch: expected {expected} bytes, observed {actual}")]
    OutputLengthMismatch { expected: u64, actual: u64 },
    #[error("output byte {value} at offset {offset} exceeds the maximum value 250")]
    OutputByteOutOfRange { offset: u64, value: u8 },
    #[error("the reopened output digests differ from the generated byte stream")]
    OutputDigestMismatch,
    #[error("failed to remove unconfirmed output {path}: {source}")]
    Cleanup {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to sync output parent {path}: {source}")]
    SyncParent {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("parent-directory synchronization is unsupported for {path}: {source}")]
    ParentDirectorySyncUnsupported {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
}

#[derive(Debug, Clone, Copy)]
struct ContributionGeometry {
    contribution_bytes: u64,
    maximum_accepted_byte: u8,
    buffer_bytes: usize,
}

impl ContributionGeometry {
    fn production() -> Result<Self, ProductionDoryV3ModelContributionError> {
        let base_input_bytes = u64::from(DORY_V3_BATCH)
            .checked_mul(u64::from(DORY_V3_DIMENSION))
            .ok_or(ProductionDoryV3ModelContributionError::GeometryOverflow)?;
        let bytes_per_layer = u64::from(DORY_V3_DIMENSION)
            .checked_mul(u64::from(DORY_V3_DIMENSION))
            .ok_or(ProductionDoryV3ModelContributionError::GeometryOverflow)?;
        let weight_bytes = u64::from(DORY_V3_LAYERS)
            .checked_mul(bytes_per_layer)
            .ok_or(ProductionDoryV3ModelContributionError::GeometryOverflow)?;
        let contribution_bytes = base_input_bytes
            .checked_add(weight_bytes)
            .ok_or(ProductionDoryV3ModelContributionError::GeometryOverflow)?;
        if contribution_bytes != FROZEN_PRODUCTION_CONTRIBUTION_BYTES
            || MAX_MODEL_BYTE != 250
            || PRODUCTION_BUFFER_BYTES > 1_048_576
        {
            return Err(ProductionDoryV3ModelContributionError::ProductionGeometryMismatch);
        }
        Ok(Self {
            contribution_bytes,
            maximum_accepted_byte: MAX_MODEL_BYTE,
            buffer_bytes: PRODUCTION_BUFFER_BYTES,
        })
    }

    fn validate(self) -> Result<(), ProductionDoryV3ModelContributionError> {
        if self.contribution_bytes == 0
            || self.maximum_accepted_byte != MAX_MODEL_BYTE
            || self.buffer_bytes == 0
            || self.buffer_bytes > 1_048_576
        {
            return Err(ProductionDoryV3ModelContributionError::ProductionGeometryMismatch);
        }
        Ok(())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct GenerationStats {
    contribution_bytes: u64,
    source_bytes_consumed: u64,
    rejected_source_bytes: u64,
    blake3: [u8; 32],
    sha256: [u8; 32],
}

#[derive(Debug)]
enum StreamGenerationError {
    Entropy(rand_core::Error),
    Write(std::io::Error),
    CountOverflow,
    BufferAllocation,
}

/// Generate one exact production contribution using only `rand_core::OsRng`.
/// Existing paths are rejected and never overwritten. No compact seed or
/// caller-selected geometry is accepted.
pub fn generate_production_dory_v3_model_contribution(
    output_path: &Path,
) -> Result<ProductionDoryV3ModelContributionReport, ProductionDoryV3ModelContributionError> {
    let geometry = ContributionGeometry::production()?;
    let mut source = OsRng;
    generate_contribution_with_source(output_path, geometry, &mut source)
}

fn generate_contribution_with_source<R: RngCore>(
    output_path: &Path,
    geometry: ContributionGeometry,
    source: &mut R,
) -> Result<ProductionDoryV3ModelContributionReport, ProductionDoryV3ModelContributionError> {
    generate_contribution_with_source_and_parent_sync(
        output_path,
        geometry,
        source,
        sync_output_parent,
    )
}

fn generate_contribution_with_source_and_parent_sync<R, P>(
    output_path: &Path,
    geometry: ContributionGeometry,
    source: &mut R,
    sync_parent: P,
) -> Result<ProductionDoryV3ModelContributionReport, ProductionDoryV3ModelContributionError>
where
    R: RngCore,
    P: FnOnce(&Path) -> Result<(), ProductionDoryV3ModelContributionError>,
{
    geometry.validate()?;
    preflight_output_path(output_path)?;
    reject_existing_output(output_path)?;

    let generation_started = Instant::now();
    let (mut output, generated) = create_generated_output_with(
        output_path,
        geometry,
        source,
        |file, bytes| file.write_all(bytes),
        Write::flush,
        File::sync_all,
    )?;
    let generation_elapsed = generation_started.elapsed();

    let verification_started = Instant::now();
    let completion = (|| {
        let verified = authenticate_generated_output(&output, geometry, &generated)?;
        sync_parent(output_path)?;
        Ok(ProductionDoryV3ModelContributionReport {
            output: output_path.to_path_buf(),
            contribution_bytes: verified.contribution_bytes,
            source_bytes_consumed: generated.source_bytes_consumed,
            rejected_source_bytes: generated.rejected_source_bytes,
            contribution_blake3: Digest32::new(verified.blake3),
            contribution_sha256: Digest32::new(verified.sha256),
            generation_elapsed_micros: elapsed_micros(generation_elapsed),
            verification_elapsed_micros: elapsed_micros(verification_started.elapsed()),
        })
    })();
    finish_or_cleanup_output(&mut output, completion)
}

fn create_generated_output_with<R, W, F, S>(
    output_path: &Path,
    geometry: ContributionGeometry,
    source: &mut R,
    mut write_chunk: W,
    flush_file: F,
    sync_file: S,
) -> Result<(PublishedContributionOutput, GenerationStats), ProductionDoryV3ModelContributionError>
where
    R: RngCore,
    W: FnMut(&mut File, &[u8]) -> std::io::Result<()>,
    F: FnOnce(&mut File) -> std::io::Result<()>,
    S: FnOnce(&File) -> std::io::Result<()>,
{
    let mut options = OpenOptions::new();
    options.read(true).write(true).create_new(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;

        options.mode(0o600);
    }
    let file = options.open(output_path).map_err(|source| {
        if source.kind() == std::io::ErrorKind::AlreadyExists {
            ProductionDoryV3ModelContributionError::OutputExists(output_path.to_path_buf())
        } else {
            ProductionDoryV3ModelContributionError::CreateOutput {
                path: output_path.to_path_buf(),
                source,
            }
        }
    })?;
    // If identity capture fails, pathname cleanup could remove a concurrent
    // replacement. Propagate the error and leave the new path for inspection.
    let retained = retained_file_identity(file, output_path)?;
    let mut output = PublishedContributionOutput {
        path: output_path.to_path_buf(),
        expected_length: geometry.contribution_bytes,
        retained: Some(retained),
        finished: false,
    };
    let mut file = match output.identity()?.as_file().try_clone() {
        Ok(file) => file,
        Err(source) => {
            let error = ProductionDoryV3ModelContributionError::CreateOutput {
                path: output_path.to_path_buf(),
                source,
            };
            return Err(cleanup_after_error(&mut output, error));
        }
    };

    let generated = match generate_stream(source, geometry, |bytes| write_chunk(&mut file, bytes)) {
        Ok(generated) => generated,
        Err(error) => {
            drop(file);
            let error = match error {
                StreamGenerationError::Entropy(source) => {
                    ProductionDoryV3ModelContributionError::Entropy(source)
                }
                StreamGenerationError::Write(source) => {
                    ProductionDoryV3ModelContributionError::WriteOutput {
                        path: output_path.to_path_buf(),
                        source,
                    }
                }
                StreamGenerationError::CountOverflow => {
                    ProductionDoryV3ModelContributionError::CountOverflow
                }
                StreamGenerationError::BufferAllocation => {
                    ProductionDoryV3ModelContributionError::BufferAllocation
                }
            };
            return Err(cleanup_after_error(&mut output, error));
        }
    };
    if let Err(source) = flush_file(&mut file) {
        drop(file);
        let error = ProductionDoryV3ModelContributionError::FlushOutput {
            path: output_path.to_path_buf(),
            source,
        };
        return Err(cleanup_after_error(&mut output, error));
    }
    if let Err(source) = sync_file(&file) {
        drop(file);
        let error = ProductionDoryV3ModelContributionError::SyncOutput {
            path: output_path.to_path_buf(),
            source,
        };
        return Err(cleanup_after_error(&mut output, error));
    }
    drop(file);
    Ok((output, generated))
}

fn generate_stream<R, W>(
    source: &mut R,
    geometry: ContributionGeometry,
    mut write_chunk: W,
) -> Result<GenerationStats, StreamGenerationError>
where
    R: RngCore,
    W: FnMut(&[u8]) -> std::io::Result<()>,
{
    let mut buffer = Vec::new();
    buffer
        .try_reserve_exact(geometry.buffer_bytes)
        .map_err(|_| StreamGenerationError::BufferAllocation)?;
    buffer.resize(geometry.buffer_bytes, 0_u8);
    let mut accepted = 0_u64;
    let mut consumed = 0_u64;
    let mut rejected = 0_u64;
    let mut blake3 = blake3::Hasher::new();
    let mut sha256 = Sha256::new();

    while accepted < geometry.contribution_bytes {
        source
            .try_fill_bytes(&mut buffer)
            .map_err(StreamGenerationError::Entropy)?;
        let remaining = geometry
            .contribution_bytes
            .checked_sub(accepted)
            .ok_or(StreamGenerationError::CountOverflow)?;
        let buffer_len_u64 =
            u64::try_from(buffer.len()).map_err(|_| StreamGenerationError::CountOverflow)?;
        let accepted_limit = usize::try_from(remaining.min(buffer_len_u64))
            .map_err(|_| StreamGenerationError::CountOverflow)?;
        let mut accepted_in_chunk = 0_usize;
        let mut examined_in_chunk = 0_usize;

        for read_index in 0..buffer.len() {
            if accepted_in_chunk == accepted_limit {
                break;
            }
            let value = buffer[read_index];
            examined_in_chunk = examined_in_chunk
                .checked_add(1)
                .ok_or(StreamGenerationError::CountOverflow)?;
            if value <= geometry.maximum_accepted_byte {
                buffer[accepted_in_chunk] = value;
                accepted_in_chunk = accepted_in_chunk
                    .checked_add(1)
                    .ok_or(StreamGenerationError::CountOverflow)?;
            }
        }

        let accepted_in_chunk_u64 =
            u64::try_from(accepted_in_chunk).map_err(|_| StreamGenerationError::CountOverflow)?;
        let examined_in_chunk_u64 =
            u64::try_from(examined_in_chunk).map_err(|_| StreamGenerationError::CountOverflow)?;
        let rejected_in_chunk = examined_in_chunk_u64
            .checked_sub(accepted_in_chunk_u64)
            .ok_or(StreamGenerationError::CountOverflow)?;
        let accepted_bytes = &buffer[..accepted_in_chunk];
        write_chunk(accepted_bytes).map_err(StreamGenerationError::Write)?;
        blake3.update(accepted_bytes);
        sha256.update(accepted_bytes);

        accepted = accepted
            .checked_add(accepted_in_chunk_u64)
            .ok_or(StreamGenerationError::CountOverflow)?;
        consumed = consumed
            .checked_add(examined_in_chunk_u64)
            .ok_or(StreamGenerationError::CountOverflow)?;
        rejected = rejected
            .checked_add(rejected_in_chunk)
            .ok_or(StreamGenerationError::CountOverflow)?;
    }

    if consumed
        != accepted
            .checked_add(rejected)
            .ok_or(StreamGenerationError::CountOverflow)?
    {
        return Err(StreamGenerationError::CountOverflow);
    }
    Ok(GenerationStats {
        contribution_bytes: accepted,
        source_bytes_consumed: consumed,
        rejected_source_bytes: rejected,
        blake3: *blake3.finalize().as_bytes(),
        sha256: finalize_sha256(sha256),
    })
}

fn authenticate_generated_output(
    output: &PublishedContributionOutput,
    geometry: ContributionGeometry,
    generated: &GenerationStats,
) -> Result<GenerationStats, ProductionDoryV3ModelContributionError> {
    let verified = verify_output(output, geometry)?;
    if verified.contribution_bytes != generated.contribution_bytes
        || verified.blake3 != generated.blake3
        || verified.sha256 != generated.sha256
    {
        return Err(ProductionDoryV3ModelContributionError::OutputDigestMismatch);
    }
    Ok(verified)
}

fn verify_output(
    output: &PublishedContributionOutput,
    geometry: ContributionGeometry,
) -> Result<GenerationStats, ProductionDoryV3ModelContributionError> {
    let mut file = output.reopen_reader()?;
    let initial_length = file
        .metadata()
        .map_err(
            |source| ProductionDoryV3ModelContributionError::ReadOutput {
                path: output.path.clone(),
                source,
            },
        )?
        .len();
    if initial_length != geometry.contribution_bytes {
        return Err(
            ProductionDoryV3ModelContributionError::OutputLengthMismatch {
                expected: geometry.contribution_bytes,
                actual: initial_length,
            },
        );
    }

    let mut buffer = Vec::new();
    buffer
        .try_reserve_exact(geometry.buffer_bytes)
        .map_err(|_| ProductionDoryV3ModelContributionError::BufferAllocation)?;
    buffer.resize(geometry.buffer_bytes, 0_u8);
    let mut observed = 0_u64;
    let mut blake3 = blake3::Hasher::new();
    let mut sha256 = Sha256::new();
    while observed < geometry.contribution_bytes {
        let remaining = geometry.contribution_bytes - observed;
        let read_limit = usize::try_from(remaining.min(buffer.len() as u64))
            .map_err(|_| ProductionDoryV3ModelContributionError::CountOverflow)?;
        let read = file.read(&mut buffer[..read_limit]).map_err(|source| {
            ProductionDoryV3ModelContributionError::ReadOutput {
                path: output.path.clone(),
                source,
            }
        })?;
        if read == 0 {
            return Err(
                ProductionDoryV3ModelContributionError::OutputLengthMismatch {
                    expected: geometry.contribution_bytes,
                    actual: observed,
                },
            );
        }
        for (index, value) in buffer[..read].iter().copied().enumerate() {
            if value > geometry.maximum_accepted_byte {
                let offset = observed
                    .checked_add(
                        u64::try_from(index)
                            .map_err(|_| ProductionDoryV3ModelContributionError::CountOverflow)?,
                    )
                    .ok_or(ProductionDoryV3ModelContributionError::CountOverflow)?;
                return Err(
                    ProductionDoryV3ModelContributionError::OutputByteOutOfRange { offset, value },
                );
            }
        }
        blake3.update(&buffer[..read]);
        sha256.update(&buffer[..read]);
        observed = observed
            .checked_add(
                u64::try_from(read)
                    .map_err(|_| ProductionDoryV3ModelContributionError::CountOverflow)?,
            )
            .ok_or(ProductionDoryV3ModelContributionError::CountOverflow)?;
    }

    let mut trailing = [0_u8; 1];
    if file.read(&mut trailing).map_err(|source| {
        ProductionDoryV3ModelContributionError::ReadOutput {
            path: output.path.clone(),
            source,
        }
    })? != 0
    {
        return Err(
            ProductionDoryV3ModelContributionError::OutputLengthMismatch {
                expected: geometry.contribution_bytes,
                actual: geometry.contribution_bytes.saturating_add(1),
            },
        );
    }
    let final_length = file
        .metadata()
        .map_err(
            |source| ProductionDoryV3ModelContributionError::ReadOutput {
                path: output.path.clone(),
                source,
            },
        )?
        .len();
    if final_length != geometry.contribution_bytes {
        return Err(
            ProductionDoryV3ModelContributionError::OutputLengthMismatch {
                expected: geometry.contribution_bytes,
                actual: final_length,
            },
        );
    }

    Ok(GenerationStats {
        contribution_bytes: observed,
        source_bytes_consumed: 0,
        rejected_source_bytes: 0,
        blake3: *blake3.finalize().as_bytes(),
        sha256: finalize_sha256(sha256),
    })
}

fn finalize_sha256(hasher: Sha256) -> [u8; 32] {
    let digest = hasher.finalize();
    let mut bytes = [0_u8; 32];
    bytes.copy_from_slice(&digest);
    bytes
}

fn preflight_output_path(output_path: &Path) -> Result<(), ProductionDoryV3ModelContributionError> {
    let file_name = output_path
        .file_name()
        .filter(|name| !name.is_empty())
        .ok_or_else(|| {
            ProductionDoryV3ModelContributionError::InvalidOutputPath(output_path.to_path_buf())
        })?;

    #[cfg(windows)]
    {
        use std::{os::windows::ffi::OsStrExt, path::Component};

        // A colon in the terminal component selects an NTFS alternate data
        // stream rather than an independent ceremony artifact. Verbatim, UNC,
        // and device namespaces also bypass ordinary Win32 path semantics.
        let has_stream_separator = file_name.encode_wide().any(|unit| unit == u16::from(b':'));
        let has_nonlocal_prefix = matches!(
            output_path.components().next(),
            Some(Component::Prefix(prefix))
                if !matches!(prefix.kind(), std::path::Prefix::Disk(_))
        );
        if has_stream_separator || has_nonlocal_prefix {
            return Err(ProductionDoryV3ModelContributionError::InvalidOutputPath(
                output_path.to_path_buf(),
            ));
        }
    }

    let _ = file_name;
    let parent = output_parent(output_path);
    let metadata = fs::symlink_metadata(parent).map_err(|source| {
        ProductionDoryV3ModelContributionError::InspectOutput {
            path: parent.to_path_buf(),
            source,
        }
    })?;
    if !metadata.file_type().is_dir() {
        return Err(ProductionDoryV3ModelContributionError::UnsafeOutputParent(
            parent.to_path_buf(),
        ));
    }

    #[cfg(windows)]
    {
        use std::os::windows::fs::MetadataExt;

        validate_windows_parent_attributes(parent, metadata.file_attributes())?;
    }

    Ok(())
}

#[cfg(windows)]
fn validate_windows_parent_attributes(
    parent: &Path,
    attributes: u32,
) -> Result<(), ProductionDoryV3ModelContributionError> {
    const FILE_ATTRIBUTE_REPARSE_POINT: u32 = 0x0000_0400;
    if attributes & FILE_ATTRIBUTE_REPARSE_POINT != 0 {
        return Err(ProductionDoryV3ModelContributionError::UnsafeOutputParent(
            parent.to_path_buf(),
        ));
    }
    Ok(())
}

fn reject_existing_output(
    output_path: &Path,
) -> Result<(), ProductionDoryV3ModelContributionError> {
    match fs::symlink_metadata(output_path) {
        Ok(_) => Err(ProductionDoryV3ModelContributionError::OutputExists(
            output_path.to_path_buf(),
        )),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(source) => Err(ProductionDoryV3ModelContributionError::InspectOutput {
            path: output_path.to_path_buf(),
            source,
        }),
    }
}

fn finish_or_cleanup_output<T>(
    output: &mut PublishedContributionOutput,
    completion: Result<T, ProductionDoryV3ModelContributionError>,
) -> Result<T, ProductionDoryV3ModelContributionError> {
    match completion {
        Ok(value) => match output.ensure_current_path() {
            Ok(()) => {
                output.confirm();
                Ok(value)
            }
            Err(error) => Err(cleanup_after_error(output, error)),
        },
        Err(error) => Err(cleanup_after_error(output, error)),
    }
}

fn cleanup_after_error(
    output: &mut PublishedContributionOutput,
    error: ProductionDoryV3ModelContributionError,
) -> ProductionDoryV3ModelContributionError {
    match output.remove_explicit() {
        Ok(()) => error,
        Err(cleanup) => cleanup,
    }
}

fn retained_file_identity(
    file: File,
    path: &Path,
) -> Result<SameFileHandle, ProductionDoryV3ModelContributionError> {
    let metadata = file.metadata().map_err(|source| {
        ProductionDoryV3ModelContributionError::InspectOutput {
            path: path.to_path_buf(),
            source,
        }
    })?;
    validate_regular_output(&metadata, path)?;
    validate_single_link(&file, &metadata, path)?;
    SameFileHandle::from_file(file).map_err(|source| {
        ProductionDoryV3ModelContributionError::InspectOutput {
            path: path.to_path_buf(),
            source,
        }
    })
}

fn regular_path_identity(
    path: &Path,
) -> Result<SameFileHandle, ProductionDoryV3ModelContributionError> {
    let metadata = fs::symlink_metadata(path).map_err(|source| {
        ProductionDoryV3ModelContributionError::InspectOutput {
            path: path.to_path_buf(),
            source,
        }
    })?;
    validate_regular_output(&metadata, path)?;
    let file = File::open(path).map_err(|source| {
        ProductionDoryV3ModelContributionError::InspectOutput {
            path: path.to_path_buf(),
            source,
        }
    })?;
    let reopened_metadata = file.metadata().map_err(|source| {
        ProductionDoryV3ModelContributionError::InspectOutput {
            path: path.to_path_buf(),
            source,
        }
    })?;
    validate_regular_output(&reopened_metadata, path)?;
    validate_single_link(&file, &reopened_metadata, path)?;
    SameFileHandle::from_file(file).map_err(|source| {
        ProductionDoryV3ModelContributionError::InspectOutput {
            path: path.to_path_buf(),
            source,
        }
    })
}

fn ensure_path_identity(
    path: &Path,
    expected: &SameFileHandle,
) -> Result<(), ProductionDoryV3ModelContributionError> {
    if &regular_path_identity(path)? != expected {
        return Err(
            ProductionDoryV3ModelContributionError::OutputIdentityMismatch(path.to_path_buf()),
        );
    }
    Ok(())
}

fn remove_file_if_identity(
    path: &Path,
    expected: &SameFileHandle,
) -> Result<(), ProductionDoryV3ModelContributionError> {
    ensure_path_identity(path, expected).map_err(|error| cleanup_error(path, error.to_string()))?;
    fs::remove_file(path).map_err(|source| ProductionDoryV3ModelContributionError::Cleanup {
        path: path.to_path_buf(),
        source,
    })
}

fn cleanup_error(
    path: &Path,
    message: impl Into<String>,
) -> ProductionDoryV3ModelContributionError {
    ProductionDoryV3ModelContributionError::Cleanup {
        path: path.to_path_buf(),
        source: std::io::Error::other(message.into()),
    }
}

fn elapsed_micros(duration: Duration) -> u64 {
    u64::try_from(duration.as_micros()).unwrap_or(u64::MAX)
}

fn validate_regular_output(
    metadata: &fs::Metadata,
    path: &Path,
) -> Result<(), ProductionDoryV3ModelContributionError> {
    if !metadata.file_type().is_file() {
        return Err(ProductionDoryV3ModelContributionError::OutputNotRegular(
            path.to_path_buf(),
        ));
    }

    #[cfg(windows)]
    {
        use std::os::windows::fs::MetadataExt;

        const FILE_ATTRIBUTE_REPARSE_POINT: u32 = 0x0000_0400;
        if metadata.file_attributes() & FILE_ATTRIBUTE_REPARSE_POINT != 0 {
            return Err(ProductionDoryV3ModelContributionError::OutputNotRegular(
                path.to_path_buf(),
            ));
        }
    }
    Ok(())
}

fn validate_single_link(
    file: &File,
    metadata: &fs::Metadata,
    path: &Path,
) -> Result<(), ProductionDoryV3ModelContributionError> {
    #[cfg(unix)]
    let links = {
        use std::os::unix::fs::MetadataExt;

        let _ = file;
        metadata.nlink()
    };

    #[cfg(windows)]
    let links = {
        use std::{mem::MaybeUninit, os::windows::io::AsRawHandle};
        use windows_sys::Win32::Storage::FileSystem::{
            BY_HANDLE_FILE_INFORMATION, GetFileInformationByHandle,
        };

        let _ = metadata;
        let mut information = MaybeUninit::<BY_HANDLE_FILE_INFORMATION>::uninit();
        // SAFETY: `file` owns a live kernel handle and `information` points to
        // writable storage of the exact structure required by the Win32 API.
        let succeeded =
            unsafe { GetFileInformationByHandle(file.as_raw_handle(), information.as_mut_ptr()) };
        if succeeded == 0 {
            return Err(ProductionDoryV3ModelContributionError::InspectOutput {
                path: path.to_path_buf(),
                source: std::io::Error::last_os_error(),
            });
        }
        // SAFETY: a nonzero return guarantees the structure was initialized.
        u64::from(unsafe { information.assume_init() }.nNumberOfLinks)
    };

    #[cfg(not(any(unix, windows)))]
    {
        let _ = (file, metadata);
        return Err(
            ProductionDoryV3ModelContributionError::HardLinkCountUnsupported(path.to_path_buf()),
        );
    }

    #[cfg(any(unix, windows))]
    if links != 1 {
        return Err(
            ProductionDoryV3ModelContributionError::UnexpectedHardLinks {
                path: path.to_path_buf(),
                links,
            },
        );
    }
    Ok(())
}

fn output_parent(path: &Path) -> &Path {
    path.parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."))
}

fn sync_output_parent(path: &Path) -> Result<(), ProductionDoryV3ModelContributionError> {
    let parent = output_parent(path);

    #[cfg(unix)]
    let directory = File::open(parent).map_err(|source| {
        ProductionDoryV3ModelContributionError::SyncParent {
            path: parent.to_path_buf(),
            source,
        }
    })?;

    #[cfg(windows)]
    let directory = {
        use std::os::windows::fs::OpenOptionsExt;

        const FILE_FLAG_BACKUP_SEMANTICS: u32 = 0x0200_0000;
        OpenOptions::new()
            .read(true)
            .write(true)
            .custom_flags(FILE_FLAG_BACKUP_SEMANTICS)
            .open(parent)
            .map_err(|source| map_parent_sync_error(parent, source))?
    };

    #[cfg(not(any(unix, windows)))]
    return Err(
        ProductionDoryV3ModelContributionError::ParentDirectorySyncUnsupported {
            path: parent.to_path_buf(),
            source: std::io::Error::new(
                std::io::ErrorKind::Unsupported,
                "this target has no implemented directory synchronization primitive",
            ),
        },
    );

    #[cfg(any(unix, windows))]
    directory
        .sync_all()
        .map_err(|source| map_parent_sync_error(parent, source))
}

fn map_parent_sync_error(
    parent: &Path,
    source: std::io::Error,
) -> ProductionDoryV3ModelContributionError {
    #[cfg(windows)]
    if source.kind() == std::io::ErrorKind::Unsupported
        || matches!(source.raw_os_error(), Some(1 | 5 | 50))
    {
        return ProductionDoryV3ModelContributionError::ParentDirectorySyncUnsupported {
            path: parent.to_path_buf(),
            source,
        };
    }

    ProductionDoryV3ModelContributionError::SyncParent {
        path: parent.to_path_buf(),
        source,
    }
}

#[derive(Debug)]
struct PublishedContributionOutput {
    path: PathBuf,
    expected_length: u64,
    retained: Option<SameFileHandle>,
    finished: bool,
}

impl PublishedContributionOutput {
    fn identity(&self) -> Result<&SameFileHandle, ProductionDoryV3ModelContributionError> {
        self.retained.as_ref().ok_or_else(|| {
            ProductionDoryV3ModelContributionError::OutputIdentityMismatch(self.path.clone())
        })
    }

    fn reopen_reader(&self) -> Result<File, ProductionDoryV3ModelContributionError> {
        ensure_path_identity(&self.path, self.identity()?)?;
        let file = OpenOptions::new()
            .read(true)
            .open(&self.path)
            .map_err(
                |source| ProductionDoryV3ModelContributionError::ReadOutput {
                    path: self.path.clone(),
                    source,
                },
            )?;
        let reopened = file.try_clone().map_err(|source| {
            ProductionDoryV3ModelContributionError::ReadOutput {
                path: self.path.clone(),
                source,
            }
        })?;
        let reopened = retained_file_identity(reopened, &self.path)?;
        if &reopened != self.identity()? {
            return Err(
                ProductionDoryV3ModelContributionError::OutputIdentityMismatch(self.path.clone()),
            );
        }
        Ok(file)
    }

    fn ensure_current_path(&self) -> Result<(), ProductionDoryV3ModelContributionError> {
        let file = self.reopen_reader()?;
        let actual = file
            .metadata()
            .map_err(
                |source| ProductionDoryV3ModelContributionError::ReadOutput {
                    path: self.path.clone(),
                    source,
                },
            )?
            .len();
        if actual != self.expected_length {
            return Err(
                ProductionDoryV3ModelContributionError::OutputLengthMismatch {
                    expected: self.expected_length,
                    actual,
                },
            );
        }
        Ok(())
    }

    fn remove_explicit(&mut self) -> Result<(), ProductionDoryV3ModelContributionError> {
        if self.finished {
            return Ok(());
        }
        let identity = self
            .retained
            .as_ref()
            .ok_or_else(|| cleanup_error(&self.path, "output identity is unavailable"))?;
        remove_file_if_identity(&self.path, identity)?;
        self.retained.take();
        self.finished = true;
        Ok(())
    }

    fn confirm(&mut self) {
        self.retained.take();
        self.finished = true;
    }
}

impl Drop for PublishedContributionOutput {
    fn drop(&mut self) {
        if !self.finished
            && let Some(identity) = self.retained.as_ref()
        {
            let _ = remove_file_if_identity(&self.path, identity);
        }
        self.retained.take();
    }
}

#[cfg(test)]
mod tests {
    use std::io::{Seek, SeekFrom};

    use super::*;

    struct ScriptedSource {
        bytes: Vec<u8>,
        offset: usize,
    }

    impl ScriptedSource {
        fn new(bytes: impl Into<Vec<u8>>) -> Self {
            Self {
                bytes: bytes.into(),
                offset: 0,
            }
        }
    }

    impl RngCore for ScriptedSource {
        fn next_u32(&mut self) -> u32 {
            panic!("the generator must use try_fill_bytes")
        }

        fn next_u64(&mut self) -> u64 {
            panic!("the generator must use try_fill_bytes")
        }

        fn fill_bytes(&mut self, _dest: &mut [u8]) {
            panic!("the generator must use fallible try_fill_bytes")
        }

        fn try_fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), rand_core::Error> {
            let end = self.offset.checked_add(dest.len()).ok_or_else(|| {
                rand_core::Error::new(std::io::Error::other("script offset overflow"))
            })?;
            let source = self.bytes.get(self.offset..end).ok_or_else(|| {
                rand_core::Error::new(std::io::Error::other("deterministic source exhausted"))
            })?;
            dest.copy_from_slice(source);
            self.offset = end;
            Ok(())
        }
    }

    fn tiny_geometry() -> ContributionGeometry {
        ContributionGeometry {
            contribution_bytes: 5,
            maximum_accepted_byte: MAX_MODEL_BYTE,
            buffer_bytes: 12,
        }
    }

    fn tiny_source() -> ScriptedSource {
        ScriptedSource::new([251, 0, 252, 250, 253, 1, 254, 2, 255, 3, 4, 5])
    }

    fn temp_path(label: &str) -> PathBuf {
        let unique = format!(
            "cmfd-dory-v3-contribution-{label}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        );
        std::env::temp_dir().join(unique)
    }

    fn create_tiny_output(path: &Path) -> (PublishedContributionOutput, GenerationStats) {
        create_generated_output_with(
            path,
            tiny_geometry(),
            &mut tiny_source(),
            |file, bytes| file.write_all(bytes),
            |_| Ok(()),
            |_| Ok(()),
        )
        .unwrap()
    }

    fn overwrite_retained(output: &PublishedContributionOutput, bytes: &[u8]) {
        let mut file = output.identity().unwrap().as_file().try_clone().unwrap();
        file.seek(SeekFrom::Start(0)).unwrap();
        file.write_all(bytes).unwrap();
        file.sync_all().unwrap();
    }

    #[test]
    fn production_geometry_preflight_is_exact_and_bounded() {
        let geometry = ContributionGeometry::production().unwrap();
        assert_eq!(geometry.contribution_bytes, 6_442_975_232);
        assert_eq!(geometry.maximum_accepted_byte, 250);
        assert_eq!(geometry.buffer_bytes, 1_048_576);
    }

    #[test]
    fn rejection_sampler_has_pinned_bytes_counts_and_hashes() {
        let mut output = Vec::new();
        let stats = generate_stream(&mut tiny_source(), tiny_geometry(), |bytes| {
            output.extend_from_slice(bytes);
            Ok(())
        })
        .unwrap();

        assert_eq!(output, [0, 250, 1, 2, 3]);
        assert_eq!(stats.contribution_bytes, 5);
        assert_eq!(stats.source_bytes_consumed, 10);
        assert_eq!(stats.rejected_source_bytes, 5);
        assert_eq!(
            hex::encode(stats.blake3),
            "bdb95bd6461b51227724ae991d208510fc7d26cb4fa699e0921df45bcad6fa02"
        );
        assert_eq!(
            hex::encode(stats.sha256),
            "9382d56be203118851d061cfe058aa6fe630d831d7f067d78c7ff465199d9ed1"
        );
    }

    #[test]
    fn tiny_generation_reopens_checks_and_hashes_exact_output() {
        let path = temp_path("success");
        let report = generate_contribution_with_source_and_parent_sync(
            &path,
            tiny_geometry(),
            &mut tiny_source(),
            |_| Ok(()),
        )
        .unwrap();

        assert_eq!(fs::read(&path).unwrap(), [0, 250, 1, 2, 3]);
        assert_eq!(report.contribution_bytes, 5);
        assert_eq!(report.source_bytes_consumed, 10);
        assert_eq!(report.rejected_source_bytes, 5);
        assert_eq!(
            report.contribution_blake3.into_bytes(),
            *blake3::hash(&fs::read(&path).unwrap()).as_bytes()
        );
        assert_eq!(
            report.contribution_sha256.into_bytes(),
            finalize_sha256(Sha256::new_with_prefix(fs::read(&path).unwrap()))
        );
        fs::remove_file(path).unwrap();
    }

    #[test]
    fn bounded_generation_exercises_the_real_parent_sync_boundary() {
        let path = temp_path("real-parent-sync");
        match generate_contribution_with_source(&path, tiny_geometry(), &mut tiny_source()) {
            Ok(report) => {
                assert_eq!(report.contribution_bytes, 5);
                fs::remove_file(path).unwrap();
            }
            Err(ProductionDoryV3ModelContributionError::ParentDirectorySyncUnsupported {
                ..
            }) if cfg!(windows) => assert!(!path.exists()),
            Err(error) => panic!("unexpected parent-sync result: {error}"),
        }
    }

    #[test]
    fn final_identity_recheck_preserves_a_parent_sync_replacement() {
        let path = temp_path("parent-sync-replacement");
        let displaced = temp_path("parent-sync-replacement-displaced");
        let error = generate_contribution_with_source_and_parent_sync(
            &path,
            tiny_geometry(),
            &mut tiny_source(),
            |output| {
                fs::rename(output, &displaced).map_err(|source| {
                    ProductionDoryV3ModelContributionError::SyncParent {
                        path: output_parent(output).to_path_buf(),
                        source,
                    }
                })?;
                fs::write(output, b"replacement").map_err(|source| {
                    ProductionDoryV3ModelContributionError::SyncParent {
                        path: output_parent(output).to_path_buf(),
                        source,
                    }
                })?;
                Ok(())
            },
        )
        .unwrap_err();

        assert!(matches!(
            error,
            ProductionDoryV3ModelContributionError::Cleanup { .. }
        ));
        assert_eq!(fs::read(&path).unwrap(), b"replacement");
        assert_eq!(fs::read(&displaced).unwrap(), [0, 250, 1, 2, 3]);
        fs::remove_file(path).unwrap();
        fs::remove_file(displaced).unwrap();
    }

    #[test]
    fn deterministic_source_failure_removes_partial_output() {
        let path = temp_path("entropy-failure");
        let error = generate_contribution_with_source_and_parent_sync(
            &path,
            ContributionGeometry {
                contribution_bytes: 5,
                maximum_accepted_byte: MAX_MODEL_BYTE,
                buffer_bytes: 4,
            },
            &mut ScriptedSource::new([0, 1, 2, 3]),
            |_| Ok(()),
        )
        .unwrap_err();

        assert!(matches!(
            error,
            ProductionDoryV3ModelContributionError::Entropy(_)
        ));
        assert!(!path.exists());
    }

    #[test]
    fn write_flush_sync_and_disk_full_failures_remove_partial_outputs() {
        let write_path = temp_path("write-failure");
        let write_error = create_generated_output_with(
            &write_path,
            tiny_geometry(),
            &mut tiny_source(),
            |_file, _bytes| Err(std::io::Error::other("injected write failure")),
            |_| Ok(()),
            |_| Ok(()),
        )
        .unwrap_err();
        assert!(matches!(
            write_error,
            ProductionDoryV3ModelContributionError::WriteOutput { .. }
        ));
        assert!(!write_path.exists());

        let disk_full_path = temp_path("disk-full");
        let disk_full_error = create_generated_output_with(
            &disk_full_path,
            tiny_geometry(),
            &mut tiny_source(),
            |_file, _bytes| Err(std::io::Error::from_raw_os_error(28)),
            |_| Ok(()),
            |_| Ok(()),
        )
        .unwrap_err();
        assert!(matches!(
            disk_full_error,
            ProductionDoryV3ModelContributionError::WriteOutput { .. }
        ));
        assert!(!disk_full_path.exists());

        let flush_path = temp_path("flush-failure");
        let flush_error = create_generated_output_with(
            &flush_path,
            tiny_geometry(),
            &mut tiny_source(),
            |file, bytes| file.write_all(bytes),
            |_| Err(std::io::Error::other("injected flush failure")),
            |_| Ok(()),
        )
        .unwrap_err();
        assert!(matches!(
            flush_error,
            ProductionDoryV3ModelContributionError::FlushOutput { .. }
        ));
        assert!(!flush_path.exists());

        let sync_path = temp_path("sync-failure");
        let sync_error = create_generated_output_with(
            &sync_path,
            tiny_geometry(),
            &mut tiny_source(),
            |file, bytes| file.write_all(bytes),
            |_| Ok(()),
            |_| Err(std::io::Error::other("injected sync failure")),
        )
        .unwrap_err();
        assert!(matches!(
            sync_error,
            ProductionDoryV3ModelContributionError::SyncOutput { .. }
        ));
        assert!(!sync_path.exists());
    }

    #[test]
    fn parent_sync_failure_removes_authenticated_output() {
        let path = temp_path("parent-sync-failure");
        let error = generate_contribution_with_source_and_parent_sync(
            &path,
            tiny_geometry(),
            &mut tiny_source(),
            |path| {
                Err(ProductionDoryV3ModelContributionError::SyncParent {
                    path: path.to_path_buf(),
                    source: std::io::Error::other("injected parent sync failure"),
                })
            },
        )
        .unwrap_err();
        assert!(matches!(
            error,
            ProductionDoryV3ModelContributionError::SyncParent { .. }
        ));
        assert!(!path.exists());
    }

    #[test]
    fn verification_rejects_corruption_range_and_length_and_cleans_up() {
        let digest_path = temp_path("digest-corruption");
        let (mut digest_output, generated) = create_tiny_output(&digest_path);
        overwrite_retained(&digest_output, &[1, 250, 1, 2, 3]);
        let digest_error =
            authenticate_generated_output(&digest_output, tiny_geometry(), &generated).unwrap_err();
        assert!(matches!(
            digest_error,
            ProductionDoryV3ModelContributionError::OutputDigestMismatch
        ));
        let digest_error =
            finish_or_cleanup_output::<()>(&mut digest_output, Err(digest_error)).unwrap_err();
        assert!(matches!(
            digest_error,
            ProductionDoryV3ModelContributionError::OutputDigestMismatch
        ));
        assert!(!digest_path.exists());

        let range_path = temp_path("range-corruption");
        let (mut range_output, generated) = create_tiny_output(&range_path);
        overwrite_retained(&range_output, &[251, 250, 1, 2, 3]);
        let range_error =
            authenticate_generated_output(&range_output, tiny_geometry(), &generated).unwrap_err();
        assert!(matches!(
            range_error,
            ProductionDoryV3ModelContributionError::OutputByteOutOfRange {
                offset: 0,
                value: 251
            }
        ));
        finish_or_cleanup_output::<()>(&mut range_output, Err(range_error)).unwrap_err();
        assert!(!range_path.exists());

        let length_path = temp_path("length-corruption");
        let (mut length_output, generated) = create_generated_output_with(
            &length_path,
            tiny_geometry(),
            &mut tiny_source(),
            |file, bytes| file.write_all(&bytes[..bytes.len() - 1]),
            |_| Ok(()),
            |_| Ok(()),
        )
        .unwrap();
        let length_error =
            authenticate_generated_output(&length_output, tiny_geometry(), &generated).unwrap_err();
        assert!(matches!(
            length_error,
            ProductionDoryV3ModelContributionError::OutputLengthMismatch {
                expected: 5,
                actual: 4
            }
        ));
        finish_or_cleanup_output::<()>(&mut length_output, Err(length_error)).unwrap_err();
        assert!(!length_path.exists());

        let trailing_path = temp_path("trailing-corruption");
        let (mut trailing_output, generated) = create_generated_output_with(
            &trailing_path,
            tiny_geometry(),
            &mut tiny_source(),
            |file, bytes| {
                file.write_all(bytes)?;
                file.write_all(&[0])
            },
            |_| Ok(()),
            |_| Ok(()),
        )
        .unwrap();
        let trailing_error =
            authenticate_generated_output(&trailing_output, tiny_geometry(), &generated)
                .unwrap_err();
        assert!(matches!(
            trailing_error,
            ProductionDoryV3ModelContributionError::OutputLengthMismatch {
                expected: 5,
                actual: 6
            }
        ));
        finish_or_cleanup_output::<()>(&mut trailing_output, Err(trailing_error)).unwrap_err();
        assert!(!trailing_path.exists());
    }

    #[test]
    fn create_new_never_overwrites_existing_output() {
        let path = temp_path("existing");
        fs::write(&path, b"keep me").unwrap();
        let error = generate_contribution_with_source_and_parent_sync(
            &path,
            tiny_geometry(),
            &mut tiny_source(),
            |_| Ok(()),
        )
        .unwrap_err();

        assert!(
            matches!(error, ProductionDoryV3ModelContributionError::OutputExists(ref found) if found == &path)
        );
        assert_eq!(fs::read(&path).unwrap(), b"keep me");
        fs::remove_file(path).unwrap();

        let directory = temp_path("existing-directory");
        fs::create_dir(&directory).unwrap();
        let error = generate_contribution_with_source_and_parent_sync(
            &directory,
            tiny_geometry(),
            &mut tiny_source(),
            |_| Ok(()),
        )
        .unwrap_err();
        assert!(matches!(
            error,
            ProductionDoryV3ModelContributionError::OutputExists(ref found) if found == &directory
        ));
        assert!(directory.is_dir());
        fs::remove_dir(directory).unwrap();
    }

    #[test]
    fn unexpected_hard_link_is_rejected_and_preserved_for_inspection() {
        let path = temp_path("hard-link");
        let link = temp_path("hard-link-alias");
        let (mut output, generated) = create_tiny_output(&path);
        fs::hard_link(&path, &link).unwrap();

        let error =
            authenticate_generated_output(&output, tiny_geometry(), &generated).unwrap_err();
        assert!(matches!(
            error,
            ProductionDoryV3ModelContributionError::UnexpectedHardLinks { links: 2, .. }
        ));
        let cleanup = finish_or_cleanup_output::<()>(&mut output, Err(error)).unwrap_err();
        assert!(matches!(
            cleanup,
            ProductionDoryV3ModelContributionError::Cleanup { .. }
        ));
        assert_eq!(fs::read(&path).unwrap(), [0, 250, 1, 2, 3]);
        assert_eq!(fs::read(&link).unwrap(), [0, 250, 1, 2, 3]);
        fs::remove_file(path).unwrap();
        fs::remove_file(link).unwrap();
    }

    #[test]
    fn replacement_is_preserved_and_cleanup_failure_is_surfaced() {
        let path = temp_path("replacement");
        let displaced = temp_path("replacement-displaced");
        let (mut output, _) = create_tiny_output(&path);
        fs::rename(&path, &displaced).unwrap();
        fs::write(&path, b"replacement").unwrap();

        let error = finish_or_cleanup_output::<()>(
            &mut output,
            Err(ProductionDoryV3ModelContributionError::OutputDigestMismatch),
        )
        .unwrap_err();
        assert!(matches!(
            error,
            ProductionDoryV3ModelContributionError::Cleanup { .. }
        ));
        assert_eq!(fs::read(&path).unwrap(), b"replacement");
        fs::remove_file(path).unwrap();
        fs::remove_file(displaced).unwrap();
    }

    #[test]
    fn nonregular_replacement_is_preserved() {
        let path = temp_path("directory-replacement");
        let displaced = temp_path("directory-replacement-displaced");
        let (mut output, _) = create_tiny_output(&path);
        fs::rename(&path, &displaced).unwrap();
        fs::create_dir(&path).unwrap();

        let error = finish_or_cleanup_output::<()>(
            &mut output,
            Err(ProductionDoryV3ModelContributionError::OutputDigestMismatch),
        )
        .unwrap_err();
        assert!(matches!(
            error,
            ProductionDoryV3ModelContributionError::Cleanup { .. }
        ));
        assert!(path.is_dir());
        fs::remove_dir(path).unwrap();
        fs::remove_file(displaced).unwrap();
    }

    #[cfg(unix)]
    #[test]
    fn existing_symlink_is_rejected_without_touching_its_target() {
        use std::os::unix::fs::symlink;

        let path = temp_path("existing-symlink");
        let target = temp_path("existing-symlink-target");
        fs::write(&target, b"target").unwrap();
        symlink(&target, &path).unwrap();

        let error = generate_contribution_with_source_and_parent_sync(
            &path,
            tiny_geometry(),
            &mut tiny_source(),
            |_| Ok(()),
        )
        .unwrap_err();
        assert!(matches!(
            error,
            ProductionDoryV3ModelContributionError::OutputExists(ref found) if found == &path
        ));
        assert_eq!(fs::read(&target).unwrap(), b"target");
        fs::remove_file(path).unwrap();
        fs::remove_file(target).unwrap();
    }

    #[cfg(unix)]
    #[test]
    fn symlink_parent_is_rejected_without_creating_an_output() {
        use std::os::unix::fs::symlink;

        let target_parent = temp_path("parent-symlink-target");
        let linked_parent = temp_path("parent-symlink");
        fs::create_dir(&target_parent).unwrap();
        symlink(&target_parent, &linked_parent).unwrap();
        let output = linked_parent.join("contribution.bin");

        let error = generate_contribution_with_source_and_parent_sync(
            &output,
            tiny_geometry(),
            &mut tiny_source(),
            |_| Ok(()),
        )
        .unwrap_err();
        assert!(matches!(
            error,
            ProductionDoryV3ModelContributionError::UnsafeOutputParent(ref found)
                if found == &linked_parent
        ));
        assert!(!target_parent.join("contribution.bin").exists());
        fs::remove_file(linked_parent).unwrap();
        fs::remove_dir(target_parent).unwrap();
    }

    #[cfg(windows)]
    #[test]
    fn alternate_data_stream_output_is_rejected_before_creation() {
        let base = temp_path("ads-base");
        fs::write(&base, b"base").unwrap();
        let mut stream_name = base.as_os_str().to_os_string();
        stream_name.push(":contribution");
        let stream = PathBuf::from(stream_name);

        let error = generate_contribution_with_source_and_parent_sync(
            &stream,
            tiny_geometry(),
            &mut tiny_source(),
            |_| Ok(()),
        )
        .unwrap_err();
        assert!(matches!(
            error,
            ProductionDoryV3ModelContributionError::InvalidOutputPath(ref found)
                if found == &stream
        ));
        assert_eq!(fs::read(&base).unwrap(), b"base");
        fs::remove_file(base).unwrap();
    }

    #[cfg(windows)]
    #[test]
    fn reparse_parent_attributes_are_rejected() {
        let parent = Path::new(r"C:\ceremony-junction");
        assert!(matches!(
            validate_windows_parent_attributes(parent, 0x0000_0410),
            Err(ProductionDoryV3ModelContributionError::UnsafeOutputParent(ref found))
                if found == parent
        ));
    }

    #[cfg(unix)]
    #[test]
    fn create_new_mode_is_0600_even_with_zero_umask() {
        const CHILD_ENV: &str = "CMFD_CONTRIBUTION_UMASK_CHILD";
        const TEST_NAME: &str =
            "dory_v3_model_contribution::tests::create_new_mode_is_0600_even_with_zero_umask";

        if std::env::var_os(CHILD_ENV).is_some() {
            use std::os::unix::fs::PermissionsExt;

            // SAFETY: this branch runs as the only selected test in a child
            // process, so changing its process-global umask cannot race a
            // sibling test.
            unsafe {
                libc::umask(0);
            }
            let path = temp_path("mode-0600");
            let (mut output, _) = create_tiny_output(&path);
            assert_eq!(
                fs::metadata(&path).unwrap().permissions().mode() & 0o777,
                0o600
            );
            output.remove_explicit().unwrap();
            return;
        }

        let status = std::process::Command::new(std::env::current_exe().unwrap())
            .args(["--exact", TEST_NAME, "--nocapture"])
            .env(CHILD_ENV, "1")
            .status()
            .unwrap();
        assert!(status.success());
    }

    #[cfg(unix)]
    #[test]
    fn symlink_replacement_is_preserved_and_not_followed_for_cleanup() {
        use std::os::unix::fs::symlink;

        let path = temp_path("symlink-replacement");
        let displaced = temp_path("symlink-replacement-displaced");
        let target = temp_path("symlink-target");
        let (mut output, _) = create_tiny_output(&path);
        fs::rename(&path, &displaced).unwrap();
        fs::write(&target, b"target").unwrap();
        symlink(&target, &path).unwrap();

        let error = finish_or_cleanup_output::<()>(
            &mut output,
            Err(ProductionDoryV3ModelContributionError::OutputDigestMismatch),
        )
        .unwrap_err();
        assert!(matches!(
            error,
            ProductionDoryV3ModelContributionError::Cleanup { .. }
        ));
        assert!(
            fs::symlink_metadata(&path)
                .unwrap()
                .file_type()
                .is_symlink()
        );
        assert_eq!(fs::read(&target).unwrap(), b"target");
        fs::remove_file(path).unwrap();
        fs::remove_file(target).unwrap();
        fs::remove_file(displaced).unwrap();
    }

    #[test]
    #[ignore = "writes and rereads the frozen 6,442,975,232-byte production contribution"]
    fn full_scale_production_generation_is_an_explicit_operator_test() {
        let path = temp_path("full-scale-ignored");
        let report = generate_production_dory_v3_model_contribution(&path).unwrap();
        assert_eq!(report.contribution_bytes, 6_442_975_232);
        assert_eq!(
            fs::metadata(&path).unwrap().len(),
            report.contribution_bytes
        );
        assert_eq!(
            report.source_bytes_consumed,
            report
                .contribution_bytes
                .checked_add(report.rejected_source_bytes)
                .unwrap()
        );

        let mut file = File::open(&path).unwrap();
        let mut buffer = vec![0_u8; PRODUCTION_BUFFER_BYTES];
        let mut observed = 0_u64;
        let mut blake3 = blake3::Hasher::new();
        let mut sha256 = Sha256::new();
        loop {
            let read = file.read(&mut buffer).unwrap();
            if read == 0 {
                break;
            }
            assert!(buffer[..read].iter().all(|value| *value <= MAX_MODEL_BYTE));
            observed = observed.checked_add(u64::try_from(read).unwrap()).unwrap();
            blake3.update(&buffer[..read]);
            sha256.update(&buffer[..read]);
        }
        assert_eq!(observed, report.contribution_bytes);
        assert_eq!(file.read(&mut [0_u8; 1]).unwrap(), 0);
        assert_eq!(
            *blake3.finalize().as_bytes(),
            report.contribution_blake3.into_bytes()
        );
        assert_eq!(
            finalize_sha256(sha256),
            report.contribution_sha256.into_bytes()
        );
        fs::remove_file(path).unwrap();
    }
}
