[package]
name = "cmfd-proof-accel"
version = "0.1.0-rc.5"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
blake3.workspace = true
fs2.workspace = true
libloading.workspace = true
same-file.workspace = true
p3-dft = { version = "=0.6.3", features = ["parallel"] }
p3-field = "=0.6.3"
p3-goldilocks = "=0.6.3"
p3-matrix = "=0.6.3"
p3-maybe-rayon = { version = "=0.6.3", features = ["parallel"] }
thiserror.workspace = true

[dev-dependencies]
p3-blake3 = "=0.6.3"
p3-commit = "=0.6.3"
p3-merkle-tree = "=0.6.3"
p3-symmetric = "=0.6.3"

[lib]
name = "cmfd_proof_accel"
path = "src/lib.rs"
