[package]
name = "cmfd-cuda"
version = "0.1.0-rc.5"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
blake3.workspace = true
cmfd-consensus = { path = "../cmfd-consensus", features = ["dory-bls12-381-prototype"] }
libloading.workspace = true

[lib]
name = "cmfd_cuda"
path = "src/lib.rs"
